name: artic
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.9
  - bcftools
  - biopython
  - bwa
  - clair3
  - clint
  - htslib
  - minimap2
  - multiqc
  - mafft
  - pandas
  - pip
  - pysam
  - pytest 
  - cyvcf2
  - requests
  - samtools
  - tqdm
